# Generated by Django 5.2.1 on 2025-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100, unique=True)),
                ('asset', models.CharField(max_length=255)),
                ('requestor', models.CharField(max_length=100)),
                ('requestor_location', models.CharField(max_length=255)),
                ('checkout_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_checkout', models.BooleanField(default=True)),
            ],
        ),
    ]
